### ISSUE TITLE
Open links in web browser instead of Electron

### ISSUE THREAD

**Issue by BNolet** [alicerunsonfedora/hyperspace#20]
Currently clicking on a link will open the webpage in another Electron window rather than in a system's default web browser

**Comment by alicerunsonfedora** [comment]
I'm hoping to fix some of this up in different methods:
* If possible, try to have a component that can render.
* For links, open in a new tab/browser.

Unfortunately, on the latter, I am unsure if there is a way to detect Electron instances versus the web version.

**Comment by BNolet** [comment]
For the latter you can use the navigator.userAgent property

From electron, this results on the following:

```
> console.log(navigator.userAgent)
VM205:1 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) 
Hyperspace/0.4.0 Chrome/69.0.3497.106 Electron/4.0.4 Safari/537.36
```

**Comment by alicerunsonfedora** [comment]
Now I guess to figure out how to make the `<a>` tags in post content follow this through. Part of the issue is that the links are directly given from the post content when fetching statuses, and they usually just do an `href` to the source.

**Comment by BNolet** [comment]
This might be of use: https://github.com/electron/electron/blob/master/docs/api/shell.md#shellopenexternalurl

**Comment by alicerunsonfedora** [comment]
I could also use this, too. The only issue is, say, getting that to work with post content. The field for `content` returns HTML content, like this:
```html
<p><a href="https://mastodon.social/@alicerunsonfedora">@alicerunsonfedora</a>: Is that working?</p>
```

It's the same reason why you can't click a username in a post's content and see the profile via the profile panel. I'll need to write a method to extract all `a` tags and replace them, but there might be a better way...

**Comment by BNolet** [comment]
What about this? https://www.npmjs.com/package/electron-open-link-in-browser

**Comment by alicerunsonfedora** [comment]
This should help with some of the steps. So far, this appears to be the best method of action:

1. Take the content and store it in a temporary `div` element.
2. Iterate over every `a` element and append `onClick` to them.
3. Set the post contents to the new div and destroy the old one.

**Comment by BNolet** [comment]
Seems straightforward but I feel like it's a pretty heavy transaction for the desired effect.

What if you caught the new window event and used that to `shell.openExternal()`?

**Comment by alicerunsonfedora** [comment]
I started experimenting with `open-external` but it seems as if the web version breaks due to it running Electron-specific code. There's definitely a few things that I'll need to work out for this to fully work.

**Comment by BNolet** [comment]
Looks like it doesn't add too much bloat to the actual code but of course I still worry it'll be too...memory-leaky

**Comment by alicerunsonfedora** [comment]
Most npm modules I could find don't do the job correctly, if at all. I've delegated the capabilities to two areas:

- `index.html` - This is the actual logic for determining how to open the link.
- `src/utilities/anchorInBrowser.js` - This is the logic that magically converts anchor tags.

Thus far, I only call `anchorInBrowser` on specified components when the component is updated.

**Comment by BNolet** [comment]
What about trying this in CSS? https://developer.mozilla.org/en-US/docs/Web/CSS/:active

use :active to append the onClick

**Comment by alicerunsonfedora** [comment]
I'm not entirely sure how this would look in terms of the code. 🤔

Not to mention, I'd need to add this CSS to every component that would contain a link...

**Comment by alicerunsonfedora** [comment]
I just updated the codebase a little bit so that calling `anchorInBrowser` only occurs after the component is mounted. This should reduce the number of times the function is called, as well as make the changes take effect immediately.

**Comment by BNolet** [comment]
Fantastic! For the CSS, I would use a universal stylesheet and then check the DOM for "repaints" or whatever it's called

**Comment by alicerunsonfedora** [comment]
I'll have to do some digging there, though I do indeed have a universal stylesheet thanks to SCSS. You're also more than welcome to check out the PR and resulting code.

**Comment by BNolet** [comment]
I'm not fluent in JS but I looked at your first point in the PR. Just be careful you're not stripping image links because you might want to open images in a lightbox unless `right-click>view image in browser`

**Comment by alicerunsonfedora** [comment]
Media attachments and post content are separate items on statuses, so there's no need to worry.
