### ISSUE TITLE
Clicking anywhere on Toot should open thread

### ISSUE THREAD

**Issue by BNolet** [alicerunsonfedora/hyperspace#26]
Clicking on a given toot should open the thread corresponding to that toot

Platform: Electron
Operating System: Ubuntu 18.10

**Comment by alicerunsonfedora** [comment]
I'm not sure if this would be completely necessary given the fact that 0.4.0 will introduce a new 'Show thread' button.

![screen shot 2019-02-11 at 08 56 36](https://user-images.githubusercontent.com/13445064/52567767-0d8ddf00-2ddb-11e9-9f47-b03024ada18c.png)

**Comment by BNolet** [comment]
The show thread button is certainly a welcome addition but I feel like also being able to click/tap on the toot itself would be nice too. Up to you

**Comment by alicerunsonfedora** [comment]
I can definitely see a use for this in the mobile context. Given that Boost Cards can now properly open their threads, I don't see why I can't implement the same thing to the post itself.

**Comment by BNolet** [comment]
Awesome! Glad to hear it!!
