### ISSUE TITLE
Only display the icons at a certain minimal width.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [alicerunsonfedora/hyperspace#30]
![2019-02-18_16-49-48](https://user-images.githubusercontent.com/13170204/52963023-0187bb80-339f-11e9-9d49-53b8d03c0140.gif)

You can see that the text overlap with a certain minimal width, which is ironically, the one this app is being displayed at by default for me.
![untitled-1](https://user-images.githubusercontent.com/13170204/52962893-b8d00280-339e-11e9-8bce-37e6f4895712.png)
You can try to aim for just isolating the icons, making it save quite a lot of space.

**Comment by alicerunsonfedora** [comment]
I'd love to get this working properly! It's been an issue for a while, though I am not sure how this scales accordingly with the PivotItem. I'll need to check the docs regarding Pivots on the Fabric UI component and see if this can be done.

https://developer.microsoft.com/en-us/fabric#/components/pivot

**Comment by alicerunsonfedora** [comment]
It turns out that I don't even need to do something with the item itself. I just passed in a `span` element with some Bootstrap properties to mitigate the issue:

```html
<span className="d-none d-lg-block">My feed</span>
```
