### ISSUE TITLE
Hum... You did applied the new icons ? 

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [alicerunsonfedora/hyperspace#42]
![2019-02-27_17-28-59](https://user-images.githubusercontent.com/13170204/53506180-b7e15400-3ab5-11e9-9ab3-402efe6a4bcf.gif)

**Comment by alicerunsonfedora** [comment]
I'll make a new Windows icon for a quick hotfix that backports some Mac App Store version stuff (like the new window command and the try/catch around the dev tools).

**Comment by alicerunsonfedora** [comment]
Triaging to 0.6.0

**Comment by alicerunsonfedora** [comment]
@PoorPocketsMcNewHold The `winicon` branch should have a fixed Windows icon, though it needs testing.

**Comment by alicerunsonfedora** [comment]
Changes should be present in master branch now
