### ISSUE TITLE
Feature Request: have compose toot box accessible from any location on the page

### ISSUE THREAD

**Issue by rubahness** [alicerunsonfedora/hyperspace#54]
Currently the compose box is fixed to the top of the page.  After scrolling down through a TL, there's no easy way to get back to write a new toot without losing your place

**Comment by alicerunsonfedora** [comment]
Given that the compose box is its own component (`<ComposeWindow>`), I don't see why it can't be done.

**Comment by alicerunsonfedora** [comment]
![Compose button](https://user-images.githubusercontent.com/13445064/54794316-32b50f00-4c1d-11e9-9306-655df4f5792e.gif)

Current changes should be available in the `composable` branch.
