### ISSUE TITLE
Use modal window animation from middle instead of slide in from the side

### ISSUE THREAD

**Issue by BNolet** [alicerunsonfedora/hyperspace#56]
When clicking/tapping on an individual toot, the "pop-in" window comes from the side, kind of counter-intuitive and slightly jarring. Would it be possible for the toot itself to expand into a modal window that centers? 

Something like the "content" modal displayed [here](https://www.youtube.com/watch?v=kXuXfaetch4&feature=youtu.be&t=12&ab_channel=BrainstormForce)

**Comment by alicerunsonfedora** [comment]
While a modal window does make sense and I can theoretically pull it off, I don't see how this could be implemented without violating Fabric UI guidelines. The Panel is commonly used for more complex tasks, and modals are commonly associated with dialogs that perform simple actions.

Reference:
* [Modal]( https://developer.microsoft.com/en-us/fabric#/components/modal)
* [Panel](https://developer.microsoft.com/en-us/fabric#/components/panel)

**Comment by BNolet** [comment]
From your link to the modal description, the end of the first paragraph:
>or for hosting heavier temporary content.

I would consider a thread to be heavier temporary content :P

**Comment by alicerunsonfedora** [comment]
Ah, I see it now. However, I'm not sure how this UI could be implemented so that it uses a modal instead of a panel due to the general nature of threads. I'll postpone this to a later Hyperspace release when I can figure out a decent UI that uses it.

**Comment by BNolet** [comment]
Not a problem :+1:

**Comment by alicerunsonfedora** [comment]
I have a basic idea for how the new thread panel system will work:

![Hyperspace Context Redesign](https://user-images.githubusercontent.com/13445064/54310414-b67d5480-45a8-11e9-88a9-955477c06026.png)

- The 'Reply' and 'Show thread' buttons on posts that aren't in a thread will be replaced with 'Show context'. This will open up a new context UI.
- To make a reply to any particular post in the thread, anyone can click 'Reply to'. With the new `Composable` component (#77), this will automatically set the `reply_to` ID, so you know that you are replying to that one (I might put a star or something to indicate which of the posts you're replying to).
- On the right is a `Composable` component used to write a response and contains all of the same features as a reply window.

I have yet to work out details, but it's a start.

**Comment by BNolet** [comment]
noice stuff!
