### ISSUE TITLE
[Electron] Clicking link to uploaded media results in unusable desktop app

### ISSUE THREAD

**Issue by BNolet** [alicerunsonfedora/hyperspace#57]
Because there's no navigation buttons in the electron app, clicking on the link corresponding to uploaded media (like in the screenshot) results in loading the picture, but in the electron app, leaving the user with an unusable app. 

![image](https://user-images.githubusercontent.com/10198484/54086541-a3f0ea00-4320-11e9-8b09-c21ee3ec0253.png)

**Comment by alicerunsonfedora** [comment]
Look like the `anchorInBrowser()` function isn't properly applied to these links.
