### ISSUE TITLE
Add a warning/Change or remove your warning inconsistency

### ISSUE THREAD

**Issue by BNolet** [alicerunsonfedora/hyperspace#59]
The modal window title/description for adding a content warning changes depending on whether the setting is activated or not:

Disabled:
![image](https://user-images.githubusercontent.com/10198484/54086605-38f3e300-4321-11e9-8b88-de26c0cf453a.png)

Enabled: 
![image](https://user-images.githubusercontent.com/10198484/54086608-43ae7800-4321-11e9-95f6-bdcf3524423e.png)

**Comment by alicerunsonfedora** [comment]
Yes, this is intended. It doesn't really make sense for it to be static if you already have a warning in place, so it changes depending on when the setting is enabled or not.

**Comment by BNolet** [comment]
I agree, however, it might be better to use more general language that fits both whether the warning is enabled or not

**Comment by alicerunsonfedora** [comment]
This should hopefully resolve ambiguity.
![image](https://user-images.githubusercontent.com/13445064/54147839-6caa3800-4409-11e9-86f3-e97f8483f407.png)
