### ISSUE TITLE
Keep the menu bar visible as we scroll down the feed

### ISSUE THREAD

**Issue by narFnarF** [alicerunsonfedora/hyperspace#61]
Currently, as we scroll down the feed, we lose quick access to other contexts (Home, Local, Public, Direct messages and notifications).

![Imgur](https://i.imgur.com/WCKxw8v.png)

**Suggestion:** Add these buttons in the top bar.

**Comment by alicerunsonfedora** [comment]
Due to the way the tabs are created in Hyperspace, I'm not sure how I'd implement the tabs directly into the navigation bar. But I don't see why I can't make it a sticky header.
