### ISSUE TITLE
No ability to add or view alt text for images

### ISSUE THREAD

**Issue by adamk678** [alicerunsonfedora/hyperspace#63]
Image descriptions is important to accessibility for people on the fediverse using screen readers. Making it easy to add these text descriptions to images is an important part of supporting that. I won't want to upload images through Hyperspace if it's impossible or difficult to add alt text using it. I really like this client otherwise and will feel comfortable recommending it to many more people once this is supported. Thanks for the rest of your work on it.

**Comment by alicerunsonfedora** [comment]
I'll need to add a section to add such things. I can't guarantee this will make the 0.7 release, but it'll be on the roadmap.

**Comment by alicerunsonfedora** [comment]
The Composable element should bring in a new change where you can add these descriptions as necessary:

![image](https://user-images.githubusercontent.com/13445064/54652741-58f87480-4a8e-11e9-828f-58fa41543f59.png)

**Comment by alicerunsonfedora** [comment]
Also, these descriptions can be viewed on posts by hovering over the item.
