### ISSUE TITLE
Feature Request: Do not update timeline if it is scrolled a bit

### ISSUE THREAD

**Issue by MasterGroosha** [alicerunsonfedora/hyperspace#66]
**How it looks now**: whenever new post in specific timeline appears, it is immediately shown and older posts go down a bit. 

**What’s bad about it**: if you started reading a long post, you have to keep scrolling down.

**Possible solution**: if user scrolled timeline even a bit, stop adding new posts to timeline, somthat it won’t move and prevent comfortable reading.

**Comment by narFnarF** [comment]
I agree, this would be really nice.

Possible solutions:
1) as suggested by @MasterGroosha , the timeline stop scrolling. You can see this behaviour in the main mastodon web interface.
2) You could also stop refreshing the timeline from the server, or just display "5 new toots" in a button that the user must press to refresh the timeline. This behaviour can be seen in the _Pinafore_ mastodon web interface.

**Comment by alicerunsonfedora** [comment]
I do have some updates, and I am able to find something from React's own documentation (go figure), but I'm probably going to postpone this for now. If/when I start a redesign, I'll probably be better implementing things and the overall post roll so that I can take full advantage without these 'loose strings'.

**Comment by alicerunsonfedora** [comment]
For reference: https://reactjs.org/docs/react-component.html#getsnapshotbeforeupdate

**Comment by alicerunsonfedora** [comment]
I should probably mention this now but in the Hyperspace redesign (WIP), I've managed to fix this issue.

<img width="691" alt="Screen Shot 2019-03-30 at 20 54 24" src="https://user-images.githubusercontent.com/13445064/55404868-e0ca8e00-5526-11e9-8d4f-ef1201f69722.png">
