### ISSUE TITLE
Boosts have object Object as tooltip

### ISSUE THREAD

**Issue by BNolet** [alicerunsonfedora/hyperspace#78]
![image](https://user-images.githubusercontent.com/10198484/54316151-6c9b6b00-45b6-11e9-882a-a9509d54e719.png)

**Comment by alicerunsonfedora** [comment]
It looks like Fabric's `DocumentCardTitle` also manipulates the tooltip text. Because the title field actually displays HTML content and not a string, it's throwing this. I might just rewrite the BoostCard component entirely to avoid this.

**Comment by alicerunsonfedora** [comment]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/13445064/54375006-9b691e00-4656-11e9-90bf-d8668b8748a4.png">

Boost cards will no longer use `DocumentCard` (but uses `DocumentCardActivity` at the bottom)

**Comment by alicerunsonfedora** [comment]
Closing this issue as it was resolved already

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
