### ISSUE TITLE
Unable to login on web version

### ISSUE THREAD

**Issue by likeadragonmaid** [alicerunsonfedora/hyperspace#83]
When I try to login my account on https://classicspace.marquiskurt.net/ or https://hyperspaceapp-next.herokuapp.com/ it tells that my account is invalid. My account is in this form XxxxxxXxxxx@niu.moe

**Comment by alicerunsonfedora** [comment]
Hmm, it seems to be able to connect to your instance just fine, and I just used test@niu.moe. Could you provide a screenshot if possible? It might be network-related or something wrong with the instance itself.

**Comment by alicerunsonfedora** [comment]
Also, please file any new issues on hyperspacedev/hyperspace instead of this one. This repository is mostly here for compatibility/legacy reasons, and the new repo will be the next version to replace this one.

**Comment by likeadragonmaid** [comment]
For some reason it is working now. Maybe it was some kind of temporary issue with the instance. Thanks for help.
